### ISSUE TITLE
Please Donate Smarter Codes

### ISSUE THREAD

**Issue by Tristan79** [Tristan79/iBrew#2]
Please donate raw output from either the console or a wireshark from the smarter coffee.
Also please run the sweep function to map out the commands of the machine!

Signed!
      Trixwood

**Comment by jkellerer** [comment]
Hi Tristan, 

What I can offer may not be exactly what you want as my target was to integrate SC with FHEM which is based on Perl5. Codes have already been added into a working integration: [FHEM/98_SmarterCoffee.pm](https://github.com/jkellerer/fhem-smarter-coffee/blob/master/fhem/FHEM/98_SmarterCoffee.pm)

I aggregated findings from other projects (including yours for the bitmasks, thanks for that!) and had to make only little use of Wireshark to get the missing parts like getting states for carafe detection (4c7e => 4d(00|01)7e) and single cup mode (4f7e => 50(00|01)7e).

Most communication logic is in the first 300 lines of the script (except discovery). 

Cheers, Juergen

**Comment by Tristan79** [comment]
I will update the 3 new commands I did not have, and the 2 new response
messages... plus that the status code is wrong i thought it would be the
same as the kettle, 0x14 and you got 0x32...

Could you run the sweep function? I would love to see some out output from
that...

./iBrew dump sweep ipcoffee

Anyway thanks!

**Comment by Tristan79** [comment]
And are you sure the waterlevel is 1 byte? For the kettle some use 1 and some 2.. and i think with the the hints of the calibration level message it is 2 bytes. 

But I do not think the smarter coffee has a calibration command? And I can not imagen it sends if wifi strength.

<STATUSCOFFEE><WATERLEVEL><WIFISTRENGTH???/WATERSENSORBITSLOW???><STRENGTH><CUPS>"

so is it:

<WATERLEVEL-HIGHBITS><WATERLEVEL-LOWBITS>
or
<WATERLEVEL><WIFISTRENGTH>
or something else?

**Comment by jkellerer** [comment]
From the app I have not seen any calibration but I was wondering why. 
The coffee amount cannot really be calibrated and it really may differ depending on the brand.

The "Status Message" as I receive it looks like this:

`32 06 13 00 02 49 7e`

`06` -> Status (8 bits)
`#3` -> Water level (lower 4 bits)
`00` -> ?? this is always "00" so far.
`#2` -> Strength (lower 4 bits), first 4 bits are always unset.
`#9` -> Cups (lower 4 bits)

Comments:

- Water level: No idea what first 4 bits do, it does not seem to relate with the water level. 
  The hex byte can be either "0" or "1", eventually it indicates the direction 
  (e.g. half to full => 1 and full to half => 0) but I need to test this to be sure (just filled it up => 13).
- Cups: First 4 bits vary over time but it does not seem to relate to the cups selection. 
  It may be that the WLAN strength is encoded here.


iBrew dump sweep (after some fixing... I'll send a PR later):
~~~~~
Message Send:     [Get device info] [647e]
Message Received: [Device info] [6502167e]
SmarterCoffee v22
---
Message Send:     [Coffee Single Mode Status] [4f7e]
Message Received: [Single cup mode status] [50007e]
Single cup mode: False
---
Message Received: [Command status] [03007e]
Command replied: Success
Message Send:     [Coffee Carafe Required Status] [4c7e]
Message Received: [Carafe status] [4d007e]
Carafe present: 0
---
Message Received: [Command status] [03007e]
Command replied: Success
Connected to SmarterCoffee Firmware v22 (192.168.2.69)

Status         Filter, OK to start
Water sensor   19
Setting        medium 1 cup

iBrew: Press ctrl-c to stop

---
iBrew: Testing Command: 46
Message Send:     [Unknown Message] [46]
Message Received: [Unknown Message] [4708010000020200190001010001000000000000000000000000000000000000007d010000020200190001010001000000000000000000000000000000000000007d010000020200190001010001000000000000000000000000000000000000007d010000020200190001010001000000000000000000000000000000000000007d010000020200190001010001000000000000000000000000000000000000007d0100000c0c00190001010000000000000000000000000000000000000000007d000100000000190001010000000000000000000000000000000000000000007d000100000000190001010000000000000000000000000000000000000000007d7e]
Unknown Reply Message

4708
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
0100000c0c0019000101000000000000000000000000000000000000000000
00010000000019000101000000000000000000000000000000000000000000
00010000000019000101000000000000000000000000000000000000000000
7e
---
iBrew: New Command Found: 46 
< ???
---
iBrew: Testing Command: 48
Message Send:     [Unknown Message] [48]
Message Received: [Unknown Message] [49050201147e]
Unknown Reply Message
Message Received: [Command status] [03007e]
Command replied: Success
iBrew: New Command Found: 48  
< Returns previously set "defaults" as <CUPS><STRENGTH><GRINDER><HOTPLATE_MINUTES>
---
iBrew: Testing Command: 4b
Message Send:     [Unknown Message] [4b]
Message Received: [Command status] [03047e]
Command replied: Failed
iBrew: New Command Found: 4b 
< ???
---
iBrew: Testing Command: 4e
Message Send:     [Unknown Message] [4e]
Message Received: [Command status] [03047e]
Command replied: Failed
iBrew: New Command Found: 4e 
< ???
~~~~~

**Comment by Tristan79** [comment]
47 08 payloadcount

your history.

01000002020019000101000100000000000000000000000000000000000000
you brewed 2 cups, and the last "1 bit" means succes :-) 

01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
01000002020019000101000100000000000000000000000000000000000000
0100000c0c0019000101000000000000000000000000000000000000000000
00010000000019000101000000000000000000000000000000000000000000
00010000000019000101000000000000000000000000000000000000000000
7e

:-)

**Comment by Tristan79** [comment]
Next week I can borrows SmarterCoffee so I can thoroughly check that part of protocol and code out. I building a little web interface at the moment, already finished most of the rest api stuff!

**Comment by jkellerer** [comment]
Thanks for the explanation on the history, I'll likely add this as well to complete my integration.

I made some minor adjustments to your code to let it do the scanning (just some missing "self." and other minor stuff). Do you want me to finish the PR before next week or do you prefer to fix it yourself?

**Comment by Tristan79** [comment]
I rewrote most of the console code, I was used to c very long time ago, not python, so still learning ;-)... and I am going to test it next week with a coffee machine, also, rest api interface (almost done) and web interface (it's abeginning...)

anyway... see homepage....

**Comment by Tristan79** [comment]
With 4b and 4e you can set the carafe present and the single cup mode, I spend two days ago a whole night remotely accessing a coffee machine to test the code...

**Comment by Tristan79** [comment]
HA! I had remote access to a coffee machine (again) today... ju4ia asked me to help him get the coffee fully working... and it is... :-)

Try:
02 01 01 01 01 01 01 14 10

( i still have not figured the time out, also used in history :-/ )

Try:
40 01 01 01 01 01 01 14 10

Try:
41

You get 

42 01 01 01 01 01 01 14 10 7d 7e

you probably can store more times settings here... (7d) but alas no coffee machine to test with... :-)
Just to let you know...  maybe the kettle can do this too.. ;-)

The extra bit in the water status, means if you can brew or not (with the water available)... I think that's what it means....   it resulted in 03 07 7e with low water, and bit 1 set... brew one cup... (forgot to check if the last 7 bit is brew failed of the status)... it changes to 0... keeps 1 all the time...

anyway....

**Comment by jkellerer** [comment]
I can confirm the extra bit in the water level. It is set when the configured number of cups is brewable. The status matches what can be calculated manually: `Max-Cups = Water-Level-Percentage (0%, 25%, 50%, 100%) * 12`.

Regarding 4b & 4e: In my fhem integration I decided not to allow disabling carafe detection as the official app forces you to accept a disclaimer before you can disable it (you bypass safety features). The text is somewhat similar to the following (I only have the german translation not the english original): "The user disabling carafe detection is responsible for ensuring that the carafe is present before starting a brew. If this user starts a brew without inserting the carafe, he does this at his own risk for body injury and property damage." This may already be covered within the OS license but I'd be careful still.

**Comment by Tristan79** [comment]
It brews into the filter which is closed until you but something beneath it.
Also since it not detects how full the carafe is and you can add water to the machine "in between",  so the same conditions can be had when carafe detection is on. (e.g. too much water in the filter)...
I accidentally triggered that... I could see it through a webcam :-) Happens when you are not the one physically operating the machine :-)

I could not use the app, it complaints it wants firmware updates, and it is not my machine, not going to do that remotely... so I still have no idea what the single cup mode does.

also I think the other 4 bits in cups are the amount of cups max possible Something like:

HaveCups = min(Water-Level-Percentage (0%, 25%, 50%, 100%) * cups,cups).

I got the scheduler/timers to work... (almost) i got it to auto-brew in 1 minute (waking up a whole family with the grinder) and found the last missing status bit is. It is set as an event has triggered.

Of brew gives back 03 07 7E when almost empty but still can brew instead of 03 06 7e no water....
and 03 0d 7e means error in schedule...

**Comment by Tristan79** [comment]
HaveCups = min(Water-Level-Percentage (0%, 25%, 50%, 100%) * cups,cups).
 
was completely wrong, i looked at my logs and its meaning is 

the current cups brewing or if stopped the total cups last brewed. (since you can change the number of cups anytime while brewing)

Also hotplate on or off is the 7th bit (cleary visible by putting it on or off).. not the 6th... the 6th bit do have something in commen with the hotplate, it also gets set when the hotplate is turned on but when off it stays 1, brewing clears it... 

that bit and how time is stored (for event & history), and some unknown commands ;-) and I think 98% of the protocol is figured out ;-)

**Comment by jkellerer** [comment]
Thanks a lot for all your efforts!
