### ISSUE TITLE
Homebridge Smarter Coffee invalid json

### ISSUE THREAD

**Issue by bhaap** [Tristan79/iBrew#22]
Your Json config for the smarter coffee seem to be invalid.

Apparently you cannot use | in json. Wonder if you can have cmdswitch2 have two status check lines and check for two different commands rather then trying to do it with one grep.

http://imgur.com/a/8xiNK

**Comment by Tristan79** [comment]
I tested it out and it works on osx... :-) did not try on linux... will try this evening on a pi!
already updated the console command

`./ibrew coffee simulate`

`./ibrew kettle simulate`

or

with dump ;-)

`./ibrew dump coffee simulate`
