### ISSUE TITLE
Run as daemon with no stdin

### ISSUE THREAD

**Issue by biwhite** [Tristan79/iBrew#24]
Hi,  I'm trying to dockerise your app, but struggling to find a way to launch the daemon with nothing connected to stdin.  It starts OK and then immediately stops the web interface/API port.

Sample output:

2016-11-29 11:44:52,841 - INFO - iBrew: Starting Web Interface & REST API on port 2080. Press ctrl-c to stop
iBrew: Press ctrl-c to stop
2016-11-29 11:44:52,842 - DEBUG - Traceback (most recent call last):
  File "/home/app/iBrew/iBrewConsole.py", line 70, in monitor
    x = raw_input("")
EOFError: EOF when reading a line

2016-11-29 11:44:52,842 - DEBUG - EOF when reading a line

iBrew: Registered bonjour server: 944fda933277:_ibrew._tcp.:(port 2080)
2016-11-29 11:44:55,843 - INFO - iBrew: Stopped Web Interface & REST API on port 2080

I wondered if you had a way around this?

Thanks.

**Comment by Tristan79** [comment]
Well a quick hack would be...

Change this line:

File "/home/app/iBrew/iBrewConsole.py", line 70, in monitor
x = raw_input("")

to 

pass 

```
    def monitor(self):
        print "iBrew: Press ctrl-c to stop"
        
        
        dump = self.client.dump
        self.client.dump_status = True
        self.client.dump = True
        
        while True:
            try:
                pass #x = raw_input("")         <------- CHANGE THIS ON LINE 70
            except KeyboardInterrupt:
                self.quit = True
                break
            except Exception, e:
                self.quit = True
                logging.debug(traceback.format_exc())
                logging.debug(str(e))
                break
        self.client.dump = dump
        self.client.dump_status = False
        print

```

but the web part is not working partly... :-)

**Comment by Tristan79** [comment]
...its all new for me, i am no coder :-) so sometimes the first try is far from perfect coz i have no clue what i am doing or which technique to use... and i made at hindsight very poorly design choices based on incomplete knowledge :-)  In other words, its totally chopped and hacked together :-) I do not know how docker works looks handy, if you have some commands or script you use to create one, please share, i could add it to the makefile such that you can auto create it (or something like that :-) Or fork your own copy with the docker setup :-)

**Comment by Tristan79** [comment]
import time
time.sleep(5) # delays for 5 seconds

it probably better to use instead of 

pass

my cpu went to 100% after a while :-/
the monitor is only there to keep the web running... its now on my todo list to fix... cuz this is crap :-)

**Comment by biwhite** [comment]
Thanks.  I've found similar myself.  I can now run the app inside the
docker container.  I'll upload my code shortly to my github.
Still trying to find out how to get it to see my kettle reliably!

**Comment by Tristan79** [comment]
https://github.com/Tristan79/iBrew/issues/26

For that you can try an untested feature! Relay server, see above link

**Comment by Tristan79** [comment]
fixed it ;-) log files are now in /var/log/iBrew and config in /etc/iBrew if you run it as root ;-)
