### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by JotWee** [Tristan79/iBrew#26]
When first setting up iBrew on Raspberry Pi, everything worked fine. Now I see connection issues. I already tried resetting WLAN, checked IP/Port reachability, but I can't figure out what might be the problem...

```
pi@raspberrypi:~ $ ibrew info

  Starting please wait...

2016-12-02 07:03:40,681 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1004, in connect
    self.__socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2016-12-02 07:03:40,683 - DEBUG - timed out
2016-12-02 07:03:40,684 - ERROR - [192.168.192.32] Could not connect to + 192.168.192.32
Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1004, in connect
    self.__socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

Could not connect to + 192.168.192.32
2016-12-02 07:03:40,686 - DEBUG - Traceback (most recent call last):
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 47, in new
    r = fn(*args, **kwargs)
  File "/home/pi/iBrew/smarter/SmarterInterface.py", line 1012, in connect
    raise SmarterError(0,"Could not connect to + " + self.host)
SmarterError

2016-12-02 07:03:40,688 - DEBUG - 
2016-12-02 07:03:40,689 - DEBUG - 
2016-12-02 07:03:40,690 - INFO - iBrew: Could not connect to [192.168.192.32]
```

**Comment by JotWee** [comment]
What I can say: the problem start as soon as I start HomeBridge

**Comment by JotWee** [comment]
found the solution - but what is the root cause?
`ConfigParser.ParsingError: File contains parsing errors: /home/pi/.iBrew/192.168.192.32.conf
	[line 12]: '= 599\n'`

**Comment by Tristan79** [comment]
Aah, another new feature that is untested :-) 
You have to give me a tiny bit of information on how did you find out?

**Comment by JotWee** [comment]
I use the Smarter iOS app and HomeBridge on a Raspberry Pi. Sometimes it is working, but generally the iOS app cannot connect to the coffee machine when the Pi is up and running. When testing (by testing I mean trying out different things, starting stopping device, Pi, Homebridge, ...) I found, that the above mentioned conf file sometimes cannot be parsed because a '=nnn' is appended.

**Comment by Tristan79** [comment]
ok! well...

I know about the connection limitations of the appliance :-/ its a cheap esp chip with very limited  connections that why i created the relay option :-) If you only have one device you can run the relay on the pi and let both the smarter app and homebridge connect to that...   

the problem its works with only one device (cuz one ip and fixed port) so if you have both devices you can only relay one...!!! (have to still figure out a good way to use the same port for both devices, its possible i tried it, but not implemented yet)...

so for one device you can set it up as this...

to set it up unplug the power of the appliance...

run 

ibrew coffee simulate

or

ibrew kettle simulate

on the machine you going to run as relay...

setup the smarter app... quit the app...

quit the simulation, plug in the power and run the relay... (look in the readme or help, i on my phone... think the command: ibrew dump relay 10.0.0.3) where 10.0.0.3 is your static ip of your device!

change the homebridge ip to the relays ip (if on same machine 127.0.0.1)... and it should now interact as bridge with only one connection to the machine... and all other connections to your pi!

and you probably have to start it every time you start or reboot your pi... (as deamon or service)

anyway...

:-)

**Comment by Tristan79** [comment]
And i will go bug hunting tomorrow,... :-)

**Comment by Tristan79** [comment]
Ok, I changed the code a little...

on my pi (latest jessy light with example ip 10.0.0.30) i added an extra ip address to the ethernet connection with the terminal command:
 
`sudo ifconfig eth0:0 10.0.0.31`

I changed the relay such that you can run it bound to one ip... so if you have both the smarter coffee and the ikettle... you can both relay it... if no bugs (?) this should speed up and clear any connection problems...  but we are in uncharted territories here... ;-)

to bind it to one ip use` ibrew relay bind_ip appliance_ip`:

so with two machines you can run:
```
./ibrew dump relay 10.0.0.30 10.0.0.98
./ibrew dump relay 10.0.0.31  10.0.0.99 
```

and set it up with the smarter app and homebridge...

(i have to write a guide for this i think :-)

**Comment by JotWee** [comment]
Thank you very much for your kind support!

**Comment by Tristan79** [comment]
I disabled stats, I found your 

`ConfigParser.ParsingError: File contains parsing errors: /home/pi/.iBrew/192.168.192.32.conf [line 12]: '= 599\n'`

error,

You where running multiple ibrew at the same time, writing to the same file at the same time, I will add something to handle that :-) probably sqlite, for now, i disabled it. So no stats on network :-) O well... So you can at least run multiple ibrew's without crashing :-) 

Without stats, it got my homebridge swinging, and my domoticz purring :-) very happy with the new http push trigger event system :-)

:-)

**Comment by JotWee** [comment]
Can the triggers be used with Homebridge as well?

**Comment by Tristan79** [comment]
Not directly, no :-)

But it can be used for SmartThings or Domoticz

Also i am planning create config files for

https://github.com/rudders/homebridge-http (which i first have to add some webstuff to it :-)

or

https://github.com/nferro/homebridge-http-json
(which should work with the rest api of ibrew at the moment, not tried yet)

I want to add the motion sensors and custom (temperature) sensors to homebridge... you know carafe present, kettle on base. :-)

Which is already possible, if you use Domoticz as bridge :-)
It has a nice homebridge plugin (https://www.npmjs.com/package/homebridge-edomoticz) to bridge all my stuff to homebridge, it has more sensors at the moment then the on/off switch with cmdswitch2... anyway. as always work in progress :-)

But i still found your bug... happy to fix that :-)

**Comment by JotWee** [comment]
Thank you very much, you're not only doing a great job, but also your support is outstanding!

**Comment by Tristan79** [comment]
Well, I was mistaken...

Can the triggers be used with Homebridge as well?

Yes they can...

https://github.com/benzman81/homebridge-http-webhooks

also is now supported....

https://github.com/rudders/homebridge-http

is now supported (i included 
http://ip:2080/api/raw/

raw api information (see & click on in the raw section)
http://ip:2080/info/api

So there are now 4 possible options to bridge to homebridge :-) 

Going to try out https://github.com/benzman81/homebridge-http-webhooks after lunch :-)
