### ISSUE TITLE
Homebridge run as a service iBrew Syntax error

### ISSUE THREAD

**Issue by Andybishop** [Tristan79/iBrew#29]
Hi, After getting Homebridge, iBrew working nice I thought it was time to get Homebridge running as a service....

I followed this guide https://timleland.com/setup-homebridge-to-start-on-bootup/ and homebridge is now running nice as a Service, however iBrew is throwing up and error and the Kettle will not turn on.. I wondered if you have seen this before the running the command systemctl status homebridge

$ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-12-04 17:30:53 GMT; 2h 49min ago
 Main PID: 1246 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─1246 homebridge

Dec 04 20:20:27 pluto homebridge[1246]: ImportError: No module named tornado.escape
Dec 04 20:20:28 pluto homebridge[1246]: [04/12/2016, 20:20:28] Failed to determine Kettle state.
Dec 04 20:20:28 pluto homebridge[1246]: [04/12/2016, 20:20:28] Traceback (most recent call last):
Dec 04 20:20:28 pluto homebridge[1246]:   File "/home/andy/iBrew/ibrew", line 4, in <module>
Dec 04 20:20:28 pluto homebridge[1246]:     from iBrewConsole import *
Dec 04 20:20:28 pluto homebridge[1246]:   File "/home/andy/iBrew/iBrewConsole.py", line 17, in <module>
Dec 04 20:20:28 pluto homebridge[1246]:     from iBrewWeb import *
Dec 04 20:20:28 pluto homebridge[1246]:   File "/home/andy/iBrew/iBrewWeb.py", line 5, in <module>
Dec 04 20:20:28 pluto homebridge[1246]:     import tornado.escape
Dec 04 20:20:28 pluto homebridge[1246]: ImportError: No module named tornado.escape

I ran Git reset --hard and then Git Pull to update iBrew and the message change to this...

:~$ systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-12-04 20:33:20 GMT; 19min ago
 Main PID: 1218 (homebridge)
    Tasks: 10 (limit: 4915)
   Memory: 75.0M
      CPU: 1min 527ms
   CGroup: /system.slice/homebridge.service
           └─1218 homebridge

Dec 04 20:53:14 pluto homebridge[1218]:      ^
Dec 04 20:53:14 pluto homebridge[1218]: SyntaxError: invalid syntax
Dec 04 20:53:15 pluto homebridge[1218]: [04/12/2016, 20:53:15] Failed to determine Kettle state.
Dec 04 20:53:15 pluto homebridge[1218]: [04/12/2016, 20:53:15] Traceback (most recent call last):
Dec 04 20:53:15 pluto homebridge[1218]:   File "/home/andy/iBrew/ibrew", line 4, in <module>
Dec 04 20:53:15 pluto homebridge[1218]:     from iBrewConsole import *
Dec 04 20:53:15 pluto homebridge[1218]:   File "/home/andy/iBrew/iBrewConsole.py", line 29
Dec 04 20:53:15 pluto homebridge[1218]:     <<<<<<< HEAD:iBrewConsole.py
Dec 04 20:53:15 pluto homebridge[1218]:      ^
Dec 04 20:53:15 pluto homebridge[1218]: SyntaxError: invalid syntax

I really appreciate all the hard work you've put into iBrew and all the help you give 👍

**Comment by Andybishop** [comment]
I suspected it may be because the service runs under the homebridge account.  I logged in as this account and tried to manually run a ibrew start and get I similar syntax error.  I will try to re-install python later under this account..

**Comment by Tristan79** [comment]
python is working but you need to install the python packages under that user, i think,  tornado is one of them (use pip & requirements.txt) the second error is a merge error (>>>>>>>HEAD... ) probably want to erase the ibrew folder and download or clone it again...

**Comment by Tristan79** [comment]
Also, you probably need to patch ibrew, see https://github.com/Tristan79/iBrew/issues/24

**Comment by Andybishop** [comment]
Got this working last night eventually, had to change permissions, re-run Python Installers and Pull iBrew etc as the Homebridge account.  But all working sweet running Homebridge as a service on Ubuntu VM.  Thanks for your help again! 👍
