### ISSUE TITLE
Cannot make any progress...

### ISSUE THREAD

**Issue by griffinnn** [Tristan79/iBrew#39]
Cannot get Linux setup to play ball...

I get as far as 'sudo make setuplin' at which point i get...

`pi@raspberrypi:~/iBrew $ sudo make setuplin
iBrew: Fetching python requirements
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22104  100 22104    0     0   130k      0 --:--:-- --:--:-- --:--:--  131k
Unpacking ./pybonjour-1.1.1.zip
  Running setup.py (path:/tmp/pip-y6TJta-build/setup.py) egg_info for package from file:///home/pi/iBrew/pybonjour-1.1.1.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-y6TJta-build/setup.py", line 32, in <module>
        import pybonjour
      File "pybonjour.py", line 109, in <module>
        _libdnssd = ctypes.cdll.LoadLibrary(_libdnssd)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
        return self._dlltype(name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libdns_sd.so.1: cannot open shared object file: No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-y6TJta-build/setup.py", line 32, in <module>

    import pybonjour

  File "pybonjour.py", line 109, in <module>

    _libdnssd = ctypes.cdll.LoadLibrary(_libdnssd)

  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary

    return self._dlltype(name)

  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__

    self._handle = _dlopen(self._name, mode)

OSError: libdns_sd.so.1: cannot open shared object file: No such file or directory

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-y6TJta-build
Storing debug log for failure in /root/.pip/pip.log
Makefile:74: recipe for target 'bonjour' failed
make: *** [bonjour] Error 1`

On the Linux version after having no luck with the OSX version. Plz halp :(

**Comment by griffinnn** [comment]
Also failing at formatting pastes from terminal :(

**Comment by Tristan79** [comment]
OSX you can use the precompiled package, which i just removed the bug causing the simlink not to be created. :-) You can run the app once in the application folder and it will symlink ibrew to /usr/local/bin, such that you can use it in a terminal by typing `ibrew`. If you move the app, just start it again to relink.

or you can run it directly from the app packages (if installed in Applications)

`/Applications/iBrew.app/Contents/MacOS/iBrewConsole`

Further! Luckily it works on any system without the bonjour package :-)
I will make it optional again... The make file was broken too, fixed that too...

Installing bonjour on any *nix system (osx, pi's, etc) use `make bonjour` but you have to have libavahi or compatible installed on a linux machine to make it work. see https://code.google.com/archive/p/pybonjour/, 

I will add that to the readme!

> Also failing at formatting pastes from terminal 

Please elaborate, you mean the http triggers?

Hope you get it to work, else I am right here :-)

**Comment by griffinnn** [comment]
Thanks for your reply Tristan. I will retry the precompiled .DMG tonight (i hit the issue you mentioned last night, clicking it and nothing was happening). 

The last bit was just me trying and failing to format my terminal paste correctly, it had been a long day! :D Will give this a goo tonight and report back.

Cheers

**Comment by griffinnn** [comment]
Tried the precompiled .dmg from the link in the readme and have same behaviour as mentioned before, double clicking it doesn't seem to do anything. Trying 'ibrew' in terminal afterwords still yields a command not found error. 

Going to update my checkout on raspberry pi and try that now...

**Comment by griffinnn** [comment]
Linux setup goes without a hitch now, thanks.

**Comment by Tristan79** [comment]
:-)
