### ISSUE TITLE
iBrew for Windows 32bit

### ISSUE THREAD

**Issue by yeello** [Tristan79/iBrew#41]
Hi Tristan79,

Is there any chance of making a Windows 32 bit version of iBrew available. I have tested it using Windows 10 64bit with Smartthings and Alexa and it works great, I would like to install it on my Windows 32 bit media centre so I can run it all the time. 

Many Thanks

Mark

**Comment by Tristan79** [comment]
Yeah, the highly sought after,  elusive and exclusive, membership & subscription based (only $5 dollar a month) x86 version of iBrew. **iBrew: 1 carrots _Diamond Edition_**. 

Maybe you could find it on the frontpage...

**Comment by Tristan79** [comment]
Any bugs let me know :-)

**Comment by yeello** [comment]
Great, works like just like a diamond edition should. Many Thanks, you have made my Christmas. 🥇
