### ISSUE TITLE
No module named tornado.escape

### ISSUE THREAD

**Issue by ijaspley** [Tristan79/iBrew#44]
Tried installing and running from source, and from dmg, and by creating dmg on mac - no task bar icon, no files in Library/Application Support, no command found for brew, no installation has happened I guess?
When I run ./ibrew I am told there is no module named tornado.escape - could this be the problem? How do I fix this please?

**Comment by ijaspley** [comment]
Traceback (most recent call last):
  File "./ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/Me/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/Me/iBrew/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

**Comment by Tristan79** [comment]
Well, if the dmg does not work,... which osx version do you run? I will have to test that on a clean osx virtual machine. 

Running from the the source, you are missing packages...  run from terminal 

` ` ` 
pip install tornado
pip install wireless
pip install datetime
` ` ` 

and you should be fine.

Please note that the front webpage is not finished, I had planned it this christmas, to learn css, javascript and stuff, but I wrote the http push "ibrew trigger event system". But the backend with rest api is working fine :-) just as the command line interface is... :-)

**Comment by Tristan79** [comment]
Ok, the ibrew link is not working, that i can fix...

For the dmg did you click:

![bypass-gatekeeper-os-x](https://cloud.githubusercontent.com/assets/4981984/21566375/d3b59406-cea2-11e6-96f7-715ecf9cc001.jpg)

(not evasion, but ibrew,... but its the first image I could find on the web)

Because iBrew will not open until you give the get-go...

**Comment by Tristan79** [comment]
Well, if the dmg works and the icon does popup :-)

And you placed the app in your Applications
you can run 

`sudo ln -s /Applications/iBrew.app/Contents/MacOS/iBrewConsole /usr/local/bin/ibrew`

to make ibrew available on the command line...  it should do it automatically,but I found the bug that is preventing it, and I do not know how to fix that... so for now it manually... :-)

**Comment by ijaspley** [comment]
Done that, now I get
My-iMac:bin Me$ ibrew
Illegal instruction: 4

**Comment by ijaspley** [comment]
I allowed launch of iBrew in Sys Pref already, I now have iBrew in usr/local/bin, I did a sudo ibrew which didn't give the Illegal instruction response but I still don't find anything on port 2080

**Comment by Tristan79** [comment]
ok! well the command is `ibrew dump server` or without dump :-)

Which osx version do you use, and is it 32bits?

Assume here, we use the source, and you unzipped it in your Documents folder.
- Open a terminal... 
- go to the source folder
- setup the packages
- run ibrew to see if it worked
- linked it to this version
- run server 
- open browser on yourip:2080

which makes
```
cd ~/Documents
cd iBrew
cd source
make setupmac
./ibrew
sudo ln -s ./ibrew /usr/local/bin/ibrew
./ibrew dump server
```

**Comment by ijaspley** [comment]
./ibrew
Traceback (most recent call last):
  File "./ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/Me/iBrew-master/source/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/Me/iBrew-master/source/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape
My-iMac:source Me$ sudo ln -s ./ibrew /usr/local/bin/ibrew
Password:
ln: /usr/local/bin/ibrew: File exists
My-iMac:source Me$ ./ibrew dump server
Traceback (most recent call last):
  File "./ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Users/Me/iBrew-master/source/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Users/Me/iBrew-master/source/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape

**Comment by Tristan79** [comment]
w8 i try it myself,

still which osx version do you use and is it 32bits?

**Comment by Tristan79** [comment]
cuz it could be 'sudo pip install tornado'...
trying w8...

**Comment by Tristan79** [comment]
ok, on a new clean osx, it seems pip should be installed first with:

sudo easy_install pip

sudo make setupmac

make should prompt you to install the command line tools..

**Comment by ijaspley** [comment]
It's El Capitan, 64 bits only now I think they are.
I Have command line tools and Xcode installed.
Getting this error after sudo make setupmac...

iBrew: Fetching python requirements
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22104  100 22104    0     0  41951      0 --:--:-- --:--:-- --:--:-- 41943
Processing ./pybonjour-1.1.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-OVtfDV-build/setup.py", line 32, in <module>
        import pybonjour
      File "pybonjour.py", line 109, in <module>
        _libdnssd = ctypes.cdll.LoadLibrary(_libdnssd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
        return self._dlltype(name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: dlopen(libSystem.B.dylib, 6): image not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-OVtfDV-build/
make: *** [bonjour] Error 1

**Comment by ijaspley** [comment]
I had done the sudo easy_install pip....

Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 9.0.1
Downloading https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz#md5=35f01da33009719497f01a4ba69d63c9
Processing pip-9.0.1.tar.gz
Writing /tmp/easy_install-3J1ZEr/pip-9.0.1/setup.cfg
Running pip-9.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3J1ZEr/pip-9.0.1/egg-dist-tmp-pwwkEN
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 9.0.1 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip

**Comment by Tristan79** [comment]
Ok, well bonjour is no problem. If the package is not there its not used...
And pip seems to be installed :-) So did it run after that?

if not try:

```
pip install tornado
pip install wireless
pip install datetime
```

**Comment by ijaspley** [comment]
pip install tornado
Requirement already satisfied: tornado in /Library/Python/2.7/site-packages
Requirement already satisfied: singledispatch in /Library/Python/2.7/site-packages (from tornado)
Requirement already satisfied: certifi in /Library/Python/2.7/site-packages (from tornado)
Requirement already satisfied: backports_abc>=0.4 in /Library/Python/2.7/site-packages (from tornado)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from singledispatch->tornado)
My-iMac:iBrew Me$ pip install wireless
Requirement already satisfied: wireless in /Library/Python/2.7/site-packages
My-iMac:iBrew Me$ pip install datetime
Requirement already satisfied: datetime in /Library/Python/2.7/site-packages
Requirement already satisfied: zope.interface in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from datetime)
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from datetime)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from zope.interface->datetime)
My-iMac:iBrew Me$ ibrew
Illegal instruction: 4

**Comment by lolfr** [comment]
Hi guys, 

I've got exactly the same issue as ijaspley. And same messages too… 
```
serveur:source shire$ ./ibrew
Traceback (most recent call last):
  File "./ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/Applications/iBrew/source/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/Applications/iBrew/source/iBrewWeb.py", line 4, in <module>
    import tornado.escape
ImportError: No module named tornado.escape
```

All the installation process are working fine, python, tornado — I try installing it by itself, with no errors —, all the make.
I gave the system the ability to launch any app (even not signed).

My server run on Sierra (64 bit).

The dmg doesn't work — no icon on the menu bar and nothing happen, plus error message on the console :
`default	21:42:15.552170 +0100	kernel	AMFI: allowing exception handler for 'iBrew' (9125) because the process is unsigned.`

However, on my MacBook Pro with Sierra, the dmg works perfectly fine. And I'm able to control the iKettle.

**Comment by Tristan79** [comment]
`default 21:42:15.552170 +0100 kernel AMFI: allowing exception handler for 'iBrew' (9125) because the process is unsigned.`

Is a gatekeeper error. it seems gatekeeper is holding it back. Try setting the security to "allow apps downloaded from anywhere" and run ibrew, see it it starts then. You should change the option back when successfully started. If not I do not have any idea.

**Comment by Tristan79** [comment]
@ijaspley: Make sure you run from the source folder `./ibrew` with the `./` to make sure you you run ibrew from that folder and not an accidential linked one in /usr/local/bin/ 

Can you remove that if you make the link `rm /usr/local/bin/ibrew`

**Comment by Tristan79** [comment]
@lolfr

update: i read to quickly you already done that... 

you should try run it from source. The only packages ibrew needs are python which is installed, and these 3:

```
pip install tornado
pip install wireless
pip install datetime
```

maybe install with sudo...???: 
`sudo pip install datetime
`

since I am running out of ideas :-) Did you Installed the brew/macports version of python...? or a newer version, because it feels like a path conflict...  or if you don't you could try that install the brew version of python 2.7...

**Comment by lolfr** [comment]
I'll probably a fresh install this weekend. Because the "only" big difference between my two Macs, is that brew (not iBrew) is already installed on the server, and it seems that there is some issue / conflict with severals python versions installed.

I'll keep you in touch.

**Comment by lolfr** [comment]
Hi Tristan,

I finally install my server from scratch (it was in the air for a moment). And now, everything is working just fine. 👍 
Next step, integrate iBrew to Homebridge so I can use Siri to control my iKettle. :-)

**Comment by Tristan79** [comment]
Ah ibrew:

You could try out: 

https://github.com/benzman81/homebridge-http-webhooks

it is on my wish list, when I get back :-) instead of polling, just push the data from ibrew server... this will be more accurate i think...

UNTESTED:

you have to use the trigger system, like in domoticz... :-)

start url: http://10.0.0.3:2080/api/10.0.0.99/start
http://10.0.0.3:2080/api/10.0.0.99/stop

where 10.0.0.3:2080 is the ibrew webserver and 10.0.0.99 is you're appliance ip.

anyway untested but here goes:

for the ikettle:

`ibrew trigger add HomeBridge KETTLEBUSY "http://yourHomebridgeServerIp:51828/?accessoryId=busy&state=§N" 10.0.0.99`

`ibrew trigger add HomeBridge OFFBASE "http://yourHomebridgeServerIp:51828/?accessoryId=base&state=§N" 10.0.0.99`

`ibrew trigger HomeBridge switch true 10.0.0.99`

(add sudo if you run as root/service, or else it will be written to a different ibrew config file)

and the config will be something like:

```
 {
        "platforms": [
            {
                "platform": "HttpWebHooks",
                "webhook_port": "51828",
                "cache_directory": "./.node-persist/storage", // (optional, default: "./.node-persist/storage")
                "sensors": [
                    {
                    "id": "base",
                    "name": "On Base",
                    "type": "motion"
                    },
                ],
                "switches": [
                    {
                    "id": "busy",
                    "name": "iKettle",
                    "on_url": " http://10.0.0.3:2080/api/10.0.0.99/start", 
                    "off_url": " http://10.0.0.3:2080/api/10.0.0.99/stop" 
                    }
                ]
            }
        ]
    }
```

**Comment by lolfr** [comment]
You are awesome !!

It's works perfectly !!!

Now I just have to play with the "options" and differents status. But the main function is working exactly as needed.

**Comment by lolfr** [comment]
One extra question… it's about the water level. How can I interpret the numbers received by the iKettle ?

**Comment by Tristan79** [comment]
See: https://github.com/Tristan79/iBrew/issues/25

**Comment by lolfr** [comment]
Ok… interesting puzzle indeed. 😅

**Comment by ijaspley** [comment]
Installed, sym link created, run ibrew in terminal, illegal instruction 4, running 10.11.6 El Capitan, 64 bit. Found this, maybe slip in to the compilers? http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by Tristan79** [comment]
pyjnstaller/python does all the magic , i am updating to osx sierra and the new xcode te see if that helps.

if that don,t work, you could run it from source like other unix setups :-) python is already installed on osx, and if you run 'make setupmac' it should install all the missing packages for you... and if missing xcode... (run 'make' to see all other options)

in the source folder run './ibrew' (with dot and slash and without quotes) to test it

if you go 'yeah!' 

then you have ibrew running using the source :-)


You do not get a fancy icon, for that you need to create a package for your system try...

if the source runs try...
'make pyinstallermac'

if that succeeds try

'make mac'

a package is created in the release folder
which hopefully would run on your system.

i tried to set up the make file that anyone can install/change and compile it...

But still strange it crashes... don't know how to debug that....

**Comment by QbaF** [comment]
Still problem with `ImportError: No module named tornado.escape` on Home Assistant on Raspbian.

**Comment by markcshaz** [comment]
I get the same issue with tornado, I understand that this was written a while ago but any chance of getting this looked at please 🙏🙏.

**Comment by jaypizzle** [comment]
Forcing the tornado version to 4.2.1 worked for me, i.e. changing the line in requirements.txt from
tornado>=4.2.1
to
tornado==4.2.1

**Comment by QbaF** [comment]
Can not find requirements.txt file in the vicinity of ibrew folder.
![image](https://user-images.githubusercontent.com/57077178/86767868-f0e7ec00-c04c-11ea-98a6-67e9f5825581.png)
Where do You @jaypizzle found it?

**Comment by jaypizzle** [comment]
I was referring to the "pure" iBrew setup, so to the requirement.txt file in the "source" folder:
https://github.com/Tristan79/iBrew/tree/master/source

I see that you're referring to the Hassio add-on, which incidentally I am also using, and in that case I managed to fix the same issue editing the Dockerfile, and in particular I've changed

`FROM $BUILD_FROM`

to 

`FROM alpine:3.9`

(in this way an older version of Alpine is used, which supports python2 version of Tornado which is no longer available in the latest Alpine).

Plus, I've updated the "apk add" line to reference python2 explicitly:

`RUN apk update && apk add bash avahi-tools avahi-compat-libdns_sd screen python2 git py-tornado jq py-pip make sudo wget`

And finally I was able to use the add-on.

**Comment by QbaF** [comment]
Thanks @jaypizzle, unfortunately, no success. Still 
`ImportError: No module named tornado.escape`

**Comment by Tristan79** [comment]
Packages are now included in the distro folder.
