### ISSUE TITLE
Beans RESTApi

### ISSUE THREAD

**Issue by arizem** [Tristan79/iBrew#46]
Hi,

first thanks for all the work.

I have some troubles with the RestApi. Im wondering about the use of beans instead of filter. May you help me with the right command for it. While using:

brew/2/0/false/strong/

It will brewing without preparing some beans. Default Set was using beans? Is there a way to force using beans with the api?

Best

Michael

**Comment by Tristan79** [comment]
I not at home but does this...

brew/2/0/beans/strong/

brew/2/0/filter/strong/

...work instead of true and false...?

i have no idea if i added an alias for true or false...

**Comment by arizem** [comment]
No this leads to the following:

Traceback (most recent call last):
  File "tornado/web.py", line 1443, in _execute
  File "iBrewWeb.py", line 587, in get
  File "smarter/SmarterProtocol.py", line 1501, in string_to_bool
SmarterErrorOld

**Comment by Tristan79** [comment]
Ok, I fixed it hopefully :-) 
You shoud be able to use 0,1 true/false beans/filter...

**Comment by arizem** [comment]
Awesome. Thanks and enjoy your trip :)

Best

Michael
