### ISSUE TITLE
LUA script for Vera (micasaverde)

### ISSUE THREAD

**Issue by mickesanda** [Tristan79/iBrew#48]
Hello, this is a request from a n00b, I own an ikettle and a smarter coffee, a Vera and Amazon Alexa.
I can control the iKettle from Alexa by creating a LUA script in a scene on Vera. I use the HA-bridge which translates all the devices and scenes to Philips HUE devices, which can be controlled from Alexa.

This is the script I use to start the iKettle:
**local hex = {
  "21", "7e",
}
local binary = "";
for i, v in ipairs(hex) do
  binary = binary .. string.char(tonumber(v, 16))
end
local socket = require("socket")
tcp = assert(socket.connect("192.168.0.199", 2081))
tcp:send(binary .. "\r\n")
luup.sleep(100)
tcp:close()
return true**

I got the smarter coffee to start with default brew with the script below, but I do not know how to set parameters for the number of cups, beans or filter or the timer for hot plate. Please help a n00B! I will post my findings to the Vera community

**local hex = {
  "0x37", 
}
local binary = "";
for i, v in ipairs(hex) do
  binary = binary .. string.char(tonumber(v, 16))
end
local socket = require("socket")
tcp = assert(socket.connect("192.168.0.129", 2081))
tcp:send(binary .. "\r\n")
luup.sleep(100)
tcp:close()
return true**

P.S. Do I need to run the iBrew or can I just write the parameters in the script? In most cases I brew 

beans/5cups/strong

Thank you in advance.

**Comment by Tristan79** [comment]
You are trying to do what ibrew does for you!

Namely bridge or translate the hex commands protocol of port 2081 to easy
to use (*uhm*, well easier) command line or rest api commands...

why don't you call ibrew from lua with os.execute?

and if it is not on the same machine use lua sockets (
http://w3.impa.br/~diego/software/luasocket/http.html) to use to rest api
of ibrew.

Just "get" (in get http) the right page... instead of using the hex
protocol :-)

For more information about the rest api run:

ibrew web

and surf to http://localhost:2080/info/api in where you can see a live demo
of the api...

i notice that the brew command is missing in the overview... another bug to
fix but it's there...

https://github.com/Tristan79/iBrew/blob/master/source/iBrewWeb.py#L1433

http://ip:2080/brew/5/6/beans/strong

5 cups 6 minutes hotplate ....

 (if you do not have the device, and it won't show up in the api overview,
simulate it! it will show up in the api! " command is ibrew coffee
simulate"!)

**Comment by Tristan79** [comment]
Editing Error, Above post should be fixed...

**Comment by mickesanda** [comment]
Good morning again,

What a fool I’ve been, I downloaded the windows64 version and ran it on my Win2012R2 virtual server. It’s unbelievable the amount of work you spent on this. Can i donate to the project?

Forget the LUA stuff, just send http commands

 

What would the syntax be to brew let’s say beans/5 cups/strong/hot plate ?

My ibrew server IP is 192.168.0.30:2080 and the smarter coffee is 192.168.0.129

Thank you again,

/Mike

 

Från: Tristan Crispijn [mailto:notifications@github.com] 
Skickat: den 11 februari 2017 22:14
Till: Tristan79/iBrew <iBrew@noreply.github.com>
Kopia: mickesanda <micke@sanda.nu>; Author <author@noreply.github.com>
Ämne: Re: [Tristan79/iBrew] LUA script for Vera (micasaverde) (#48)

 

You are trying to do what ibrew does for you!

Namely bridge or translate the hex commands protocol of port 2081 to easy
to use (*uhm*, well easier) command line or rest api commands...

why don't you call ibrew from lua with os.execute?

and if it is not on the same machine use lua sockets (
http://w3.impa.br/~diego/software/luasocket/http.html) to use to rest api
of ibrew.

Just "get" (in get http) the right page... instead of using the hex
protocol :-)

For more information about the rest api run:

ibrew web

and surf to http://localhost:2080/info/api in where you can see a live demo
of the api...

i notice that the brew command is missing in the overview... another bug to
fix but it's there...

https://github.com/Tristan79/iBrew/blob/master/source/iBrewWeb.py#L1433

http://ip:2080/brew/5/6/beans/strong

5 cups 6 minutes hotplate ....

(if you do not have the device, and it won't show up in the api overview,
simulate it! it will show up in the api! " command is ibrew coffee
simulate"!)

**Comment by mickesanda** [comment]
I almost got this working,  when i go to this URL: http://192.168.0.30:2080/brew/5/6/beans/strong

 

I see the iBrew interface with the picture of the coffee machine and the settings that are set.

However, I need to press the ”Play” symbol in order to start the process. How do I do that when sending a http get through my HA-Bridge?

Send the start command I mean… Probably stupid question….

 

Michael Sanda

micke@sanda.nu <mailto:micke@sanda.nu> 
+46(0) 709 75 96 69

 

 

 

Från: Tristan Crispijn [mailto:notifications@github.com] 
Skickat: den 11 februari 2017 22:14
Till: Tristan79/iBrew <iBrew@noreply.github.com>
Kopia: mickesanda <micke@sanda.nu>; Author <author@noreply.github.com>
Ämne: Re: [Tristan79/iBrew] LUA script for Vera (micasaverde) (#48)

 

You are trying to do what ibrew does for you!

Namely bridge or translate the hex commands protocol of port 2081 to easy
to use (*uhm*, well easier) command line or rest api commands...

why don't you call ibrew from lua with os.execute?

and if it is not on the same machine use lua sockets (
http://w3.impa.br/~diego/software/luasocket/http.html) to use to rest api
of ibrew.

Just "get" (in get http) the right page... instead of using the hex
protocol :-)

For more information about the rest api run:

ibrew web

and surf to http://localhost:2080/info/api in where you can see a live demo
of the api...

i notice that the brew command is missing in the overview... another bug to
fix but it's there...

https://github.com/Tristan79/iBrew/blob/master/source/iBrewWeb.py#L1433

http://ip:2080/brew/5/6/beans/strong

5 cups 6 minutes hotplate ....

(if you do not have the device, and it won't show up in the api overview,
simulate it! it will show up in the api! " command is ibrew coffee
simulate"!)

**Comment by Tristan79** [comment]
The JSON rest api is the backend of the server, that's the part you need!
The frontend, the nice webpage, you should ignore, it's a prototype and not
fully functional, but is has a nice overview of the backend api build in
:-).

Start ibrew web server and look at:

http://192.168.0.30:2080/info/api

(localhost your ip of the ibrew server)

every link is a working json rest api request example...

there is one missing I forgot to add it that is the brew command (and I
also incorrectly gave you the wrong link above, I discovered):

You get the following http request url's you can use in a lua script

http://192.168.0.30:2080/api/192.168.0.129/start
http://192.168.0.30:2080/api/192.168.0.129/stop

or with arguments:

http://192.168.0.30:2080/api/192.168.0.129/brew/5/6/beans/strong

for status:

http://192.168.0.30:2080/api/192.168.0.129/raw/kettlebusy
<http://192.168.0.30:2080/api/192.168.0.129/raw/kettlebusy>
which return the string True or False if requested...

where 192.168.0.30 is the ip of the ibrew web server and 192.168.0.129 is
the ip of you smarter device...

You can test the links by editing the ip's and copy them in the browser
address window or try the
http://192.168.0.30:2080/info/api overview page...

So you're question how to start it:

http://192.168.0.30:2080/api/192.168.0.129/start

If you got I working version, please post it in the issues or mail it, will
add it to the readme!

Tristan
