### ISSUE TITLE
404 on iBrew .dmg with Dropbox 

### ISSUE THREAD

**Issue by anthonyray** [Tristan79/iBrew#53]

**Comment by durosity** [comment]
Did you ever find a copy?

**Comment by WarmCatUK** [comment]
This is a shame, as it will not build on osx :-/

**Comment by durosity** [comment]
Yeah I’ve not had any luck with that, not that I’m particularly competent at such things.  I’m gonna try over Christmas to use some of the python to integrate it into my existing domotics controller.. a bit of bodging here and a hammer there and I should be able to get it to show up in HomeKit.  That’ll at least make the smart part of the kettle useful to me!

Also just read your blog entries, you have lovely cats :)

**Comment by WarmCatUK** [comment]
Thanks! They're both being lazy today, freezing outside so the fire is on :-)
I kinda got it working, found mention of installing:
pip install tornado
pip install wireless
Now I can run "python ibrew"
I'm not entirely sure how I got that far though...

**Comment by durosity** [comment]
Ah that could be useful info, I’ll give it a try later.. i didn’t have much luck last time I tried, but I’m determined to get it to work!

Yeah mine too.. snow confuses the heck out of the young ones.  I don’t think they’ve ever seen it before.  All melted now though.

**Comment by Onlinedispatcher** [comment]
Hey,
did you ever succeed build or getting a DMG package?
Thanks a lot

**Comment by WarmCatUK** [comment]
Hi, I never got a DMG compiled.  
I ended up using the python code, but it was a year ago now and my memory is terrible. I then used a Philips hue emulator and openHAB so that Alexa could turn on/off the kettle.

**Comment by Tristan79** [comment]
You do not need the dmg package. Will try to recreate one. Python packages now included in the distro folder just unzip them in the source folder if needed.
