### ISSUE TITLE
client.coffee_brew() Argument failure

### ISSUE THREAD

**Issue by gesv** [Tristan79/iBrew#56]
Hi
Thanks for you work with this code.
I noticed when I tried the WebAPI that the client_coffee_brew had some misplaced arguments.
When I changed the strenght from weak to strong my coffee did not brew, and the webserver throw me an exception that the hotplate was out of range.

I dive into the code and noticed that Smarter.string_to_strength(strength) is the second argument, but should be the last one.
Original:
client.coffee_brew(Smarter.string_to_cups(cups),Smarter.string_to_strength(strength),Smarter.string_to_hotplate(hotplate),Smarter.string_to_grind(grind))

So I modified this line of code to:
client.coffee_brew(Smarter.string_to_cups(cups),Smarter.string_to_hotplate(hotplate),Smarter.string_to_grind(grind),Smarter.string_to_strength(strength))

And now I can drink my coffee in peace ;)

**Comment by Tristan79** [comment]
That was a bug! Fixed.
