### ISSUE TITLE
Webserver not responding/working after installation

### ISSUE THREAD

**Issue by chaugan** [Tristan79/iBrew#58]
**Using Smarter Coffee**

I'm currently successfully (as I see it) iBrew on a Pi and I get a successfull connection to my coffee maker. I can control it from console and everything.

But when I try to access the web interface, the webserver won't respond.

I see that the service is up on the port 2080 in netstat, and it states in the console that it is up and running. But when i try to access the website, nothing happens. The web browser just keeps waiting and waiting and waiting.

I've verified that my computer can access the port 2080 on the Pi (and there is no FW).

I even can't access the website locally on the pi through SSH with console browsers like `Links`. Same thing happens there as a normal browser on a normal computer.

I've tried locally both hostname, localhost and 127.0.0.1. On the computer, I've tried both IP and hostname.

What can be wrong? No error messages found.

**Comment by DennisVonDerBey** [comment]
@chaugan Have you found out what the problem was? I am in the same position as you.

**Comment by DennisVonDerBey** [comment]
I found the fix. The 'tornado' requirement that handles the web overlay is installed with the latest version. It seems like it had a breaking change in the last two years, so it doesn't work. I hardcoded the version in my requirements.txt to 4.2.1 and it now it works like a charm. :)

**Comment by netRunner0** [comment]
@DennisVonDerBey Can you find out how you did it?

**Comment by Tristan79** [comment]
Tornado package now included in distro folder
