### ISSUE TITLE
New Hardware

### ISSUE THREAD

**Issue by Tristan79** [Tristan79/iBrew#61]
So my kettle broke down... there are only v3 available with the uncertainty of not reversing the protocol (too much money to try) so I have been looking at the alternatives...

With "open" protocols:
Currently my eye falls on:

https://github.com/aprosvetova/xiaomi-kettle
https://github.com/drndos/mikettle
(can not turn on through bluetooth)

and 

https://github.com/PimenovAlexander/r4s-bluetooth
https://redmond.company/nl/products/sky-kitchen/kettle-redmond-rk-m170s-e/

both bluetooth (not wifi)... Do any you have any other recommendation about "open" kettles? (or coffee machines or kitchen stuff?)

**Comment by Tristan79** [comment]
Ow... An AppKettle is out of the question, no local network support (cloud based)... we do not want cloud or internet... only local

**Comment by durosity** [comment]
Unfortunately I’ve not found any others that seem suitable.  The AppKettle is the closest but no local support is insane (I mean why do we need cloud support for a kettle.. of all the “IoT” things out there external access to a kettle seems utterly pointless).  At this point I’m tempted to just get one with a digital switch on the base to turn it on and just solder on a little z-wave relay or something like that.

Glad to see you back!

**Comment by Tristan79** [comment]
I got one of the last ones after combing the web :-) 

https://www.digitalstrom.de/Shop/Plug-Play/Smarter-iKettle-2-0.html

now ibrew is not working... probably some package changes in python... and after two years... the documentation is very bad... **_curse you iBrew developer!!!_**

Also ordered the xiaomi one with bluetooth to play with (since it dirt cheap and my pi has bluetooth :-) and will probably order the redmond kettle if I have mo-money... currently as broke as my original ikettle... Going to try to add them both to iBrew and clean up the code the next couple of weeks... (still have to process the pull request for the Samsung thingy...)

**Comment by DJay-X** [comment]
I'm using iBrew and iKettle 2 since 2017 together with my Homebridge on Pi. Wouldn't want to muss it. Although, Xiaomi Kettle would be also worth a try. I hope you will also have homebridge in mind while developing. 👍 I run and Pi Zero W with Bluetooth in addition to the main Pi Homebridge, so ready to test. ;) 
Thanks again for your work @Tristan79

**Comment by DJay-X** [comment]
@Tristan79 First of all, I hope you are doing well.
Any news on Xiaomi Kettle automation from your side? 
The base of my iKettle 2.0 broke a bit after 3 years now. 
So I am starting to to look for alternatives to use a Kettle with homebridge / HomeKit.
Do you still considering to work on something like this?
Thx.

**Comment by Tristan79** [comment]
No. I got a second ikettle.
