### ISSUE TITLE
Homebridge-cmd4 "support"

### ISSUE THREAD

**Issue by misanthrophy** [Tristan79/iBrew#62]
Hi,

first and foremost, thanks for the great development. I just received my iKettle today and added it to homebridge with the cmdswitch2. I can now switch it on and switch it off just fine.

In your help (terminal) I found a few additional commands like:

`heat start heating water

stop stop heating water

65C select temperature 65°c

80C select temperature 80°c

95C select temperature 95°c

100C select temperature 100°c

warm start keep water warm

5m select 5 minutes keep water warm

10m select 10 minutes keep water warm

20m select 20 minutes keep water warm

status Get status`

Of course I could just simply create a few other switches for different temperatures etc. But it would be much better, if I could get slider for temp and/or keep water warm inside a single "device". I found another plugin which could potentially resolve this:
https://github.com/ztalbot2000/homebridge-cmd4

Here an example of the script:
https://github.com/ztalbot2000/homebridge-cmd4#step-3--contents-of-ps4sh
And here how it looks like depending on the devicetype in the config.json:
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/Extras/config.json

Do you think, that your work is capable of working with these and if so, is there aaaaany chance that you could provide an example how it should look like? If you can work something out, I am sure, there are some people who would happy donate for your hard work :-)

**Comment by DJay-X** [comment]
Great idea. It would be amazing to have this functionality.
I also love your work @misanthrophy and wouldn't want to miss iBrew, because of also using it with homebridge since years successfully.

**Comment by Tristan79** [comment]
I will look into it... I also have no domoticz sliders or action buttons so that is coming too...
And I am playing with mqtt (https://pypi.org/project/paho-mqtt/) but I am not sure about that.. probably more for my homemade hardware projects... 

Too much toys to play with :-)

Ow... and... DJay-X (before the edit)
https://github.com/Tristan79/iBrew/blob/master/source/iBrewConsole.py#L48
I just have fun making stuff for myself (and per accident, you guys). So no donations...

**Comment by misanthrophy** [comment]
Looking forward to your work! If there is anything I can provide you with to support your work or debugging just let me know!
