### ISSUE TITLE
Triggers use GET instead of POST

### ISSUE THREAD

**Issue by thexperiments** [Tristan79/iBrew#66]
I just wanted to integrate the triggers with Home Assistant so that I don't have to poll the status all the time.

However Home Assistant expects a POST request for webhooks and that can't be changed.

Maybe this could be reworked to use POST instead of GET

```
The following example uses the POST method instead:

>>> import urllib
>>> params = urllib.urlencode({'spam': 1, 'eggs': 2, 'bacon': 0})
>>> f = urllib.urlopen("http://www.musi-cal.com/cgi-bin/query", params)
>>> print f.read()
```

https://github.com/Tristan79/iBrew/blob/master/source/smarter/SmarterInterface.py#L1287

**Comment by Tristan79** [comment]
Probably looking at the line number you gave, i only checked/tested if the conversion was succesfull, to what you described above... haven't tried calling urllib, since no work machine at the moment...

```
if s[0:4] == "http":
    try:
        response = urllib.urlopen(s)
    except Exception, e:
        print str(e)

# new code to insert starts here! 

# put get before the http to get it not post it,... :-)
# example trigger: s = "get http://smarthome.local/?idx=§O&value=§N" will translate in
# a dictionary with the parameters and the base url, which you can call urllib.urlopen to get it...

elif s[0:8] == "get http":
    pos = s.find('?')
    base = s[4:pos]
    listparams = s[pos+1:].split('&')
    params = urllib.urlencode({ i.split('=')[0] : i.split('=')[1] for i in listparams })
    try:
        response = urllib.urlopen(base, params)
        print response.read()
    except Exception, e:
        print str(e)

# old code continues....

else:
    r = os.popen(s).read()
    if self.dump:
        print r
```

**Comment by Tristan79** [comment]
The two triggers functions to add code to are located here:

https://github.com/Tristan79/iBrew/blob/master/source/smarter/SmarterInterface.py#L4330
https://github.com/Tristan79/iBrew/blob/master/source/smarter/SmarterInterface.py#L1287

**Comment by Tristan79** [comment]
Hope it works!

**Comment by Tristan79** [comment]
Included in source iBrew :-)
