### ISSUE TITLE
Is that project alive?

### ISSUE THREAD

**Issue by QbaF** [Tristan79/iBrew#72]
I've tried to install it on my previous machine (under Home Assistant).  Unfortunately no success. Now I changed host and would like to give it (or rather me) another try but found that add-on is no longer working. 
I am motivated to try it harder but isn't it pointless? does it work for Home Assistant on 64bit Debian?

**Comment by Tristan79** [comment]
iBrew has not changed, and I have no control over the add-on from home
assistant...
you should post your issue there.
